version: '3.9'
services:

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: webchat
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: wordpass
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres.data:/var/lib/postgresql/users:rw
#      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  centrifugo:
    image: centrifugo/centrifugo:v5.4.2
    volumes:
      - ./config/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json --health --swagger
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 5s

  webchat-service:
    container_name: webchat-service
    build:
      context: webchat-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
#      centrifugo:
#        condition: service_healthy



volumes:
  postgres.data: { }
  data: { }

#networks:
#  shared-network:
#    driver: bridge
#    name: shared-network