spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sanity
    password: wordpass
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate.format_sql: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
springdoc:
  api-docs:
    path: /swagger/api-docs
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        transaction: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
application:
  channels:
    centrifugo:
      api-key: api_key
  security:
    jwt:
      key: ${CENTRIFUGO_JWT_KEY}
      ttl-min: 2
  storage:
    minio:
      access-key: Q3AM3UQ867SPQQA43P2F
      secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG