spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webchat
application:
  channels:
    centrifugo:
      base-url: http://localhost:8000
  storage:
    minio:
      host: localhost
      port: 9000
      secure: false
