spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/webchat
application:
  channels:
    centrifugo:
      base-url: http://centrifugo:8000
  storage:
    minio:
      host: nginx
      port: 9000
      secure: false